### ISSUE TITLE
Old catkin dependency 

### ISSUE THREAD

**Issue by dcconner** [CNURobotics/flexbe_behavior_engine#1]
I get this when trying to install with Colcon. I assumed the Catkin instructions were just legacy documentation? Or do I actually need to install Catkin on Ros2?

Foxy on 20.04

ubuntu@ubuntu:/dev_ws/src$ ls
build flexbe_app flexbe_behavior_engine install log
ubuntu@ubuntu:/dev_ws/src$ colcon build
Starting >>> flexbe_msgs
--- stderr: flexbe_msgs
CMake Error at CMakeLists.txt:4 (find_package):
By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "catkin", but
CMake did not find one.

Could not find a package configuration file provided by "catkin" with any
of the following names:
catkinConfig.cmake
catkin-config.cmake

Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
"catkin_DIR" to a directory containing one of the above files. If "catkin"
provides a separate development package or SDK, be sure it has been
installed.

Failed <<< flexbe_msgs [0.92s, exited with code 1]

Summary: 0 packages finished [2.32s]
1 package failed: flexbe_msgs
1 package had stderr output: flexbe_msgs
9 packages not processed
ubuntu@ubuntu:~/dev_ws$ sudo apt install ros-foxy-ament-cmake-python
Reading package lists... Done
Building dependency tree
Reading state information... Done
ros-foxy-ament-cmake-python is already the newest version (0.9.9-1focal.20210901.021729).

**Comment by Jmz919** [comment]
Removed all packages with any reference to catkin
